apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aviatrix-network-policy-controller.fullname" . }}
  namespace: {{ .Values.mcpRuntimeNamespace }}
rules:
  - apiGroups: ["networking.aviatrix.com"]
    resources: ["firewallpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aviatrix-network-policy-controller.fullname" . }}
  namespace: {{ .Values.mcpRuntimeNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aviatrix-network-policy-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aviatrix-network-policy-controller.fullname" . }}
