apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aviatrix-network-policy-controller.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "aviatrix-network-policy-controller.name" . }}
